### ISSUE TITLE
Poggies

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [SAElizondoR/Interpolacion-Lagrange#1]
⢠⣤⣀⠀⠀⠀⠀⠀⠀⠀⢰⢦⡀⠀⢰⢆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠙⣎⠙⠲⢤⣀⠀⠀⠀⡌⠈⣗⣄⡌⠘⣷⣀⣠⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠈⢦⡀⠀⠈⠙⠲⢄⣣⡖⣯⡷⣧⠀⢸⢿⣦⡀⠈⠳⣦⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠳⡄⠀⠀⠀⠈⣿⣼⣯⣄⣿⣦⣸⢸⣏⠻⣤⣀⣈⣷⡄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠈⠳⢤⠤⠴⠻⣯⠈⠋⠙⠃⠀⠈⣿⠻⣾⡿⠛⠁⠉⣦⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⡰⠋⠀⠀⠀⠀⣠⣴⣄⠀⠀⠀⠈⠷⣤⡛⠛⢿⣿⡟⢹⡄⠀⠀
⠀⠀⠀⠀⢀⡜⠁⠀⠀⠀⠀⠀⢻⠿⠿⠀⠀⠀⠀⠀⠈⢻⡙⢹⡏⠿⣆⣹⠀⠀
⠀⠀⠀⢀⡞⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠾⢷⡞⠁⣀⠙⢿⠂⠀
⠀⠀⢀⢾⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢷⡀⣿⠀⢸⡄⠀
⠀⠀⡞⠘⢧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡾⣷⣾⠇⠀
⠀⢸⠈⠿⠀⠙⠲⣄⠀⠀⢀⣀⣀⣀⣀⣠⠀⠀⠀⠀⠀⠀⠀⠀⣸⠇⢀⣼⠀⠀
⠀⠀⠳⣄⠀⠀⠀⣘⠷⠊⠉⠀⠀⠀⠀⠀⢃⠀⠀⠀⠀⠀⢴⣶⠿⠖⠛⣿⡄⠀
⠀⠀⠀⠀⠉⠛⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠘⣄⠀⢀⣠⠖⠋⠀⠀⠀⠀⠀⠉⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

**Comment by SAElizondoR** [comment]
uwu
